# Generated by Django 2.1.5 on 2019-01-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='time_tv',
            field=models.CharField(default='', max_length=20),
        ),
    ]
