# Generated by Django 2.1.5 on 2019-01-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_auto_20190121_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_time'], 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
