# Generated by Django 2.1.5 on 2019-01-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_auto_20190121_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='news_comment', to='app_news.News'),
        ),
    ]
