# Generated by Django 2.1.5 on 2019-01-21 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20190121_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuanziModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duanzi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '段子',
                'verbose_name_plural': '段子',
                'db_table': 'duanzi',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
